"""Shared pytest fixtures for Aura Frames tests."""
import pytest


@pytest.fixture
def sample_frame_data():
    """Sample frame data as returned by the API."""
    return {
        'id': '728893d7-55c2-41ea-bb08-61281546dd40',
        'name': 'Test Frame',
        'user_id': 'user-123',
        'software_version': '1.5.1027',
        'build_version': '20251218.192401',
        'hw_android_version': '8.1.0',
        'created_at': '2025-01-01T00:00:00.000Z',
        'updated_at': '2025-01-01T00:00:00.000Z',
        'handled_at': '2025-01-01T00:00:00.000Z',
        'deleted_at': None,
        'updated_at_on_client': '2025-01-01T00:00:00.000Z',
        'orientation': 0,
        'auto_brightness': True,
        'min_brightness': 1,
        'max_brightness': 255,
        'brightness': None,
        'sense_motion': True,
        'default_speed': None,
        'slideshow_interval': 600,
        'slideshow_auto': False,
        'digits': 1234,
        'contributors': None,
        'contributor_tokens': [],
        'hw_serial': 'TEST-123',
        'matting_color': 'BLACK',
        'trim_color': 'WHITE',
        'is_handling': False,
        'calibrations_last_modified_at': '2025-01-01T00:00:00.000Z',
        'gestures_on': True,
        'portrait_pairing_off': None,
        'live_photos_on': False,
        'auto_processed_playlist_ids': [],
        'time_zone': 'UTC',
        'wifi_network': 'TestWifi',
        'cold_boot_at': None,
        'is_charity_water_frame': False,
        'num_assets': 100,
        'thanks_on': True,
        'frame_queue_url': 'https://sqs.example.com/frame',
        'client_queue_url': 'https://sqs.example.com/client',
        'scheduled_display_sleep': False,
        'scheduled_display_on_at': None,
        'scheduled_display_off_at': None,
        'forced_wifi_state': None,
        'forced_wifi_recipient_email': None,
        'is_analog_frame': False,
        'control_type': 'touch_bars',
        'display_aspect_ratio': 'landscape_16_10',
        'has_claimable_gift': False,
        'gift_billing_hint': None,
        'locale': 'en',
        'frame_type': None,
        'description': None,
        'representative_asset_id': None,
        'sort_mode': None,
        'email_address': 'test@send.auraframes.com',
        'features': ['captions_release', 'mqtt_enabled'],
        'letterbox_style': None,
        'user': {
            'id': 'user-123',
            'name': 'Test User',
            'email': 'test@example.com',
            'created_at': '2025-01-01T00:00:00.000Z',
            'updated_at': '2025-01-01T00:00:00.000Z',
            'short_id': None,
            'show_push_prompt': False,
            'latest_app_version': None,
            'attribution_id': None,
            'attribution_string': None,
            'test_account': False,
            'avatar_file_name': None,
            'has_frame': True,
            'analytics_optout': False,
            'admin_account': False,
        },
        'playlists': [
            {'id': 'playlist-1', 'name': 'Album 1', 'num_assets': 50},
            {'id': 'playlist-2', 'name': 'Album 2', 'num_assets': 50},
        ],
        'delivered_frame_gift': None,
        'last_feed_item': {},
        'last_impression': None,
        'last_impression_at': '2025-01-01T00:00:00.000Z',
        'child_albums': [],
        'smart_adds': [],
        'recent_assets': [],
    }


@pytest.fixture
def sample_asset_data():
    """Sample asset data as returned by the API."""
    return {
        'id': 'asset-123',
        'user_id': 'user-123',
        'file_name': 'photo.jpg',
        'width': 1920,
        'height': 1080,
        'taken_at': '2025-01-01T12:00:00.000Z',
        'uploaded_at': '2025-01-01T12:00:00.000Z',
        'handled_at': '2025-01-01T12:00:00.000Z',
        'attachments': [],
        'selected': True,
        'data_uti': 'public.jpeg',
        'exif_orientation': 1,
        'glaciered_at': '4001-01-01T00:00:00.000Z',
        'good_resolution': True,
        'is_subscription': False,
        'local_identifier': 'local-123',
        'rotation_cw': 0,
        'source_id': 'source-123',
        'unglacierable': True,
        'upload_priority': 90,
        'user': {
            'id': 'user-123',
            'name': 'Test User',
            'email': 'test@example.com',
            'created_at': '2025-01-01T00:00:00.000Z',
            'updated_at': '2025-01-01T00:00:00.000Z',
            'short_id': None,
            'show_push_prompt': False,
            'latest_app_version': None,
            'attribution_id': None,
            'attribution_string': None,
            'test_account': False,
            'avatar_file_name': None,
            'has_frame': True,
            'analytics_optout': False,
            'admin_account': False,
        },
        # Optional fields
        'auto_landscape_16_10_rect': None,
        'auto_portrait_4_5_rect': None,
        'burst_id': None,
        'burst_selection_types': None,
        'colorized_file_name': None,
        'created_at_on_client': None,
        'duplicate_of_id': None,
        'duration': None,
        'duration_unclipped': None,
        'favorite': None,
        'hdr': None,
        'horizontal_accuracy': None,
        'ios_media_subtypes': None,
        'is_live': None,
        'landscape_16_10_url': None,
        'landscape_16_10_url_padding': None,
        'landscape_rect': None,
        'landscape_url': None,
        'landscape_url_padding': None,
        'live_photo_off': None,
        'location': None,
        'location_name': None,
        'md5_hash': None,
        'minibar_landscape_url': None,
        'minibar_portrait_url': None,
        'minibar_url': None,
        'modified_at': None,
        'orientation': None,
        'original_file_name': None,
        'panorama': None,
        'portrait_4_5_url': None,
        'portrait_4_5_url_padding': None,
        'portrait_rect': None,
        'portrait_url': None,
        'portrait_url_padding': None,
        'raw_file_name': None,
        'represents_burst': None,
        'taken_at_granularity': None,
        'taken_at_user_override_at': None,
        'thumbnail_url': None,
        'user_landscape_16_10_rect': None,
        'user_landscape_rect': None,
        'user_portrait_4_5_rect': None,
        'user_portrait_rect': None,
        'video_clip_excludes_audio': None,
        'video_clip_start': None,
        'video_clipped_by_user_at': None,
        'video_file_name': None,
        'video_url': None,
        'widget_url': None,
    }


@pytest.fixture
def sample_user_data():
    """Sample user data as returned by login API."""
    return {
        'id': 'user-123',
        'name': 'Test User',
        'email': 'test@example.com',
        'auth_token': 'test-auth-token-12345',
        'created_at': '2025-01-01T00:00:00.000Z',
        'updated_at': '2025-01-01T00:00:00.000Z',
        'short_id': None,
        'show_push_prompt': False,
        'latest_app_version': None,
        'attribution_id': None,
        'attribution_string': None,
        'test_account': False,
        'avatar_file_name': None,
        'has_frame': True,
        'analytics_optout': False,
        'admin_account': False,
    }


@pytest.fixture
def sample_attachment_data():
    """Sample attachment/caption data."""
    return {
        'id': 'attachment-123',
        'asset_id': 'asset-123',
        'frame_id': 'frame-123',
        'user_id': 'user-123',
        'type': 'caption',
        'data': 'Test caption text',
        'created_at': '2025-01-01T00:00:00.000Z',
        'updated_at': '2025-01-01T00:00:00.000Z',
    }
